version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: nomad
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nomad-web:
    image: nomad-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database