services:
  database:
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: nomad
  nomad-web:
    image: nomad-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:3000
    depends_on:
      - database